baseURL: "https://theerthanimalluri.com"
languageCode: en-us
title: Theerthani Malluri
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: certifications
      name: Certifications
      url: /certifications
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Theerthani Malluri"
    subtitle: "Hello, I'm Theerthani Malluri, a fourth-year student at Vellore Institute of Technology in Vellore. I am enthusiastic about using technology to generate good change and build unique solutions, and I have a strong problem-solving talent. Throughout my academic career, I have built a solid foundation in web development, as well as coding, and data structures. I thrive in demanding workplaces that demand critical thinking and I appreciate working together to solve complicated challenges. Aside from my technical ability, I have good communication and interpersonal skills, allowing me to work well with cross-functional teams. I'm actively looking for possibilities where I can use my problem-solving talents and enthusiasm for technology to make a difference."
    imageUrl: "home/me.jpg"
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: Resume
        url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:contact@theerthanimalluri.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/reddy-theerthani-malluri-9819aa204"
    - name: "github"
      url: "https://github.com/theerthani"
    # - name: "youtube"
    #   url: "https://www.youtube.com/c/AbdurRahmanKalim"
    # - name: "cv"
    #   url: "https://drive.google.com/file/d/1U6Gg2RnHSCthtWLbZJBlAEI3V1WGjZty/view"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
